---
- hosts: localhost
  collections:
    - kubernetes.core
  tasks:
  # Ensure Cluster is up and configured before proceeding
  - name: Wait for cluster to be ready.
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterVersion
        name: version
        wait: yes
        wait_condition:
          type: Available
          status: True

  # Wait until the MCP has the ipsec import certs machine config before proceeding
  - name: Get Master Machine Config Pool pass
    kubernetes.core.k8s_info:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      name: master
    register: mcp_state
    until: mcp_state.resources | json_query('[*].spec.configuration.source[?name ==`99-master-import-certs`]') | first | length > 0

  # We need to ensure that the MCP has been properly applied prior to trying to apply the 
  # NNCP for IPSec
  - name: Wait for Machine Config to be part of MCP
    kubernetes.core.k8s_info:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      name: master
      wait: yes
      wait_condition:
          type: Updated
          status: True

  # src file should come from a secret or configmap
  - name: Apply our NMState Config File for IPSec Creation
    kubernetes.core.k8s:
      state: present
      src: /ansible/dynamic/ipsec.yml
  
  # Ensure NNCP is configured before proceeding
  - name: Wait for NNCP for IPSec to be ready
    kubernetes.core.k8s_info:
      api_version: nmstate.io/v1
      kind: NodeNetworkConfigurationPolicy
      name: ipsec-config
      wait: yes
      wait_condition:
        type: Available
        status: True
        reason: SuccessfullyConfigured

  # In Theory, we should be able to curl the api endpoint now, we can add a curl check here to be sure it worked
  # DNS is no longer working, so for now lets test with a IP address
  - name: Check that you can connect (GET) to a page and it returns a status 200
    ansible.builtin.uri:
      url: https://172.16.25.97:6443
      validate_certs: false
      status_code: 403