---
apiVersion: v1
kind: Pod
metadata:
  name: ibi-post-config-debug
  namespace: ibi-post-config
spec:
  serviceAccountName: ibi-config
  containers:
  - image: "quay.io/markd/ibi-post-config:v2"
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    name: ibi-debug
    imagePullPolicy: Always
    resources:
      limits:
        memory: 2Gi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
    env:
    - name: K8S_AUTH_API_KEY
      value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    volumeMounts:
      - name: ipsec-cm
        mountPath: /ansible/dynamic/ipsec
      - name: acm-import-secret
        mountPath: /ansible/dynamic/acm
  volumes:
    - name: ipsec-cm
      configMap:
        name: ipsec-cm
    - name: acm-import-secret
      secret:
        secretName: acm-import-secret