---
apiVersion: v1
kind: Namespace
metadata:
  name: ibi_post_config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibi_config
  namespace: ibi_post_config

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibi_config_crb
subjects:
  - kind: ServiceAccount
    name: ibi_config
    namespace: ibi_post_config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---
apiVersion: v1
kind: Pod
metadata:
  name: ibi-post-config-debug
spec:
  containers:
  - image: "quay.io/markd/ibi-post-config:latest"
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    name: ibi-debug
    imagePullPolicy: Always
    resources:
      limits:
        memory: 2Gi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"