---
apiVersion: v1
kind: Namespace
metadata:
  name: ibi-post-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibi-config
  namespace: ibi-post-config

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibi-config-crb
subjects:
  - kind: ServiceAccount
    name: ibi-config
    namespace: ibi-post-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ibi-config
  namespace: ibi-post-config
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: ibi-config
      containers:
      - image: "quay.io/markd/ibi-post-config:latest"
        name: ibi-debug
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: K8S_AUTH_API_KEY
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        volumeMounts:
          - name: klusterlet-crd
            mountPath: /ansible/dynamic/crd
          - name: klusterlet-install
            mountPath: /ansible/dynamic
      volumes:
        - name: klusterlet-crd
          configMap:
            name: klusterlet-cm
        - name: klusterlet-install
          secret:
            secretName: klusterlet-install-secret
      # change this to OnFailure once debugging is done
      # restartPolicy: "OnFailure"
      restartPolicy: Never
  backoffLimit: 4
