---
apiVersion: v1
kind: Pod
metadata:
  name: ibi-post-config-debug
  namespace: ibi-post-config
spec:
  serviceAccountName: ibi-config
  containers:
  - image: "quay.io/markd/ibi-post-config:latest"
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    name: ibi-debug
    imagePullPolicy: Always
    resources:
      limits:
        memory: 2Gi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
    env:
    - name: K8S_AUTH_API_KEY
      value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    volumeMounts:
      - name: klusterlet-crd
        mountPath: /ansible/dynamic/crd
      - name: klusterlet-install
        mountPath: /ansible/dynamic
  volumes:
    - name: klusterlet-crd
      configMap:
        name: klusterlet-cm
    - name: klusterlet-install
      secret:
        secretName: klusterlet-install-secret
